# Generated by Django 2.0.2 on 2018-02-26 14:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='mobile',
            field=models.CharField(default=datetime.datetime(2018, 2, 26, 14, 19, 9, 69891, tzinfo=utc), max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='total_tax',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(default=datetime.datetime(2018, 2, 26, 14, 19, 9, 72514, tzinfo=utc), max_length=255, unique=True),
        ),
    ]
