# Generated by Django 2.0.2 on 2018-02-17 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0002_auto_20180217_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='permissions',
            field=models.CharField(choices=[('AD', 'Admin'), ('SL', 'Sales'), ('PU', 'Purchase'), ('AC', 'Accounts')], default='Sales', max_length=100),
        ),
    ]
