# Generated by Django 2.0.2 on 2018-02-18 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0004_auto_20180218_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='channel',
            field=models.CharField(choices=[('IN', 'In-Store'), ('ON', 'Online')], default='In-Store', max_length=100),
        ),
        migrations.DeleteModel(
            name='Channel',
        ),
    ]
