# Generated by Django 2.0.2 on 2018-02-18 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0005_auto_20180218_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='kind',
        ),
        migrations.AddField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('CA', 'Cash'), ('CC', 'Credit Card'), ('DC', 'Debit Card'), ('WA', 'Wallet'), ('UPI', 'BHIM UPI')], default='Cash', max_length=100),
        ),
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
    ]
