# Generated by Django 2.0.2 on 2018-02-26 15:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0005_auto_20180226_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.AddField(
            model_name='customer',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.CharField(blank=True, default=datetime.datetime(2018, 2, 26, 15, 55, 55, 329293, tzinfo=utc), max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(default=datetime.datetime(2018, 2, 26, 15, 55, 55, 332101, tzinfo=utc), max_length=255, unique=True),
        ),
    ]
