# Generated by Django 2.0.2 on 2018-02-19 11:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0007_auto_20180218_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('AD', 'Admin'), ('SL', 'Sales'), ('PU', 'Purchase'), ('AC', 'Accounts')], default='Sales', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_id',
            field=models.CharField(default=datetime.datetime(2018, 2, 19, 11, 42, 56, 203258, tzinfo=utc), max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='wholesale_price',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='retail_price',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=10, null=True),
        ),
        migrations.RemoveField(
            model_name='staff',
            name='permissions',
        ),
        migrations.AddField(
            model_name='staff',
            name='permissions',
            field=models.ManyToManyField(to='v1.AccessPermission'),
        ),
    ]
