# Generated by Django 2.0.2 on 2018-03-01 16:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0009_auto_20180226_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(default=datetime.datetime(2018, 3, 1, 16, 50, 40, 772763, tzinfo=utc), max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='invoice_id',
            field=models.CharField(default=datetime.datetime(2018, 3, 1, 16, 50, 40, 773463, tzinfo=utc), max_length=200, unique=True),
        ),
    ]
