# Generated by Django 2.0.2 on 2018-03-13 14:21

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0010_auto_20180301_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('CSH', 'Cash'), ('CRD', 'Credit/Debit Card'), ('WAL', 'Wallet'), ('UPI', 'BHIM UPI')], default='Cash', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(default=datetime.datetime(2018, 3, 13, 14, 21, 51, 297605, tzinfo=utc), max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='productinsale',
            name='sale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_in_sale', to='v1.Sale'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='invoice_id',
            field=models.CharField(default=datetime.datetime(2018, 3, 13, 14, 21, 51, 299387, tzinfo=utc), max_length=200, unique=True),
        ),
    ]
