# Generated by Django 2.0.2 on 2018-03-13 20:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0011_auto_20180313_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(default=datetime.datetime(2018, 3, 13, 20, 29, 9, 178198, tzinfo=utc), max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='invoice_id',
            field=models.CharField(default=datetime.datetime(2018, 3, 13, 20, 29, 9, 179268, tzinfo=utc), max_length=200, unique=True),
        ),
    ]
