# Generated by Django 2.0.2 on 2018-03-17 22:02

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0012_auto_20180313_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInPurchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_qty', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_id', models.CharField(default=datetime.datetime(2018, 3, 17, 22, 2, 44, 961687, tzinfo=utc), max_length=200, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('total_tax', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='v1.Staff')),
                ('transaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='v1.Transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('mobile', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(default=datetime.datetime(2018, 3, 17, 22, 2, 44, 959610, tzinfo=utc), max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='invoice_id',
            field=models.CharField(default=datetime.datetime(2018, 3, 17, 22, 2, 44, 960310, tzinfo=utc), max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='v1.Vendor'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='v1.Warehouse'),
        ),
        migrations.AddField(
            model_name='productinpurchase',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1.Product'),
        ),
        migrations.AddField(
            model_name='productinpurchase',
            name='purchase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_in_purchase', to='v1.Sale'),
        ),
    ]
