# Generated by Django 2.0.2 on 2018-03-20 00:00

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0013_auto_20180317_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(default=datetime.datetime(2018, 3, 20, 0, 0, 32, 735255, tzinfo=utc), max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='productinpurchase',
            name='purchase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_in_purchase', to='v1.Purchase'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchase_id',
            field=models.CharField(default=datetime.datetime(2018, 3, 20, 0, 0, 32, 738074, tzinfo=utc), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='invoice_id',
            field=models.CharField(default=datetime.datetime(2018, 3, 20, 0, 0, 32, 736220, tzinfo=utc), max_length=200, unique=True),
        ),
    ]
